# Generated by Django 3.2.5 on 2021-07-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0005_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='last_save_time',
            field=models.DateTimeField(),
        ),
    ]
